import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import SecondHeader from "@/components/common/SecondHeader";
import Navbar from "@/components/NavBar/Navbar";
import Footer from "@/components/common/Footer";
import FirstHeader from "@/components/common/FirstHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
          <FirstHeader ></FirstHeader>
          <SecondHeader ></SecondHeader>
          <Navbar  ></Navbar>
          {children}
          <Footer></Footer>
        </Providers>
      </body>
    </html>
  );
}
